// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTVf8MmOUm2LOWp_KLExy3fvaYV26cT8',
    appId: '1:517785436314:web:7149a26843d45ea2e21f23',
    messagingSenderId: '517785436314',
    projectId: 'tenant-fyp',
    authDomain: 'tenant-fyp.firebaseapp.com',
    storageBucket: 'tenant-fyp.firebasestorage.app',
    measurementId: 'G-RW5YCZEWYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiL1DOdnU20q6TFdo9exDnbBYdZEW0kaQ',
    appId: '1:517785436314:android:60ff25b8f5b3adcee21f23',
    messagingSenderId: '517785436314',
    projectId: 'tenant-fyp',
    storageBucket: 'tenant-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjTW6GFPj1e-ILgGcKcospD3R6QgCwsm4',
    appId: '1:517785436314:ios:82ecfe41eac4b710e21f23',
    messagingSenderId: '517785436314',
    projectId: 'tenant-fyp',
    storageBucket: 'tenant-fyp.firebasestorage.app',
    iosBundleId: 'com.yixiang.tenant',
  );

}